"""P8 · 供应链依赖锁结构不变量。

端到端验收(`uv pip install --require-hashes`)由 ``scripts/hash_lock.sh`` 跑;
本测试守 ``requirements.txt`` 的文件级不变量,防回归:
  - 存在
  - 每个包版本 == 锁死(无 ``>=``/``~``)
  - 每个包至少带一条 ``--hash=sha256:``(防 wheel 篡改)
"""

import re
from pathlib import Path

PROOT = Path(__file__).resolve().parents[2]
LOCK = PROOT / "requirements.txt"

# 包行:行首字母/数字,含 ==,非续行(--hash=)非注释(#)。
_PKG_RE = re.compile(r"^[A-Za-z0-9][^#]*==")


def _package_lines() -> list[str]:
    return [ln for ln in LOCK.read_text().splitlines() if _PKG_RE.match(ln)]


def test_lock_file_exists() -> None:
    """P8 产物 requirements.txt 必须在位。"""
    assert LOCK.is_file(), f"{LOCK} 缺失——P8 未完成,跑 scripts/hash_lock.sh"


def test_lock_non_empty() -> None:
    """锁文件至少有一个包。"""
    pkgs = _package_lines()
    assert pkgs, "空锁——requirements.in 为空或 compile 失败"


def test_all_versions_pinned() -> None:
    """所有依赖必须 == 精确锁死(拒绝 >= / ~ / 无版本)。"""
    for ln in _package_lines():
        head = ln.split("\\")[0].strip()
        assert "==" in head, f"未锁死: {ln!r}"
        assert not any(op in head for op in (">=", "<=", "~=", "!=")), f"非精确锁: {ln!r}"


def test_every_package_has_hash() -> None:
    """每个包至少一条 sha256 hash(supply-chain 完整性)。"""
    text = LOCK.read_text()
    n_pkg = len(_package_lines())
    n_hash = text.count("--hash=sha256:")
    assert n_hash >= n_pkg, (
        f"hash({n_hash}) < 包数({n_pkg})——存在无 hash 包,重跑 scripts/hash_lock.sh"
    )


def test_has_autogen_header() -> None:
    """uv pip compile 的自动生成头(可追溯重锁命令)。"""
    head = "\n".join(LOCK.read_text().splitlines()[:3])
    assert "autogenerated" in head.lower() or "uv pip compile" in head.lower()


# ── D-1(审查 06-14)修复回归:--audit 真审计 + 消息不过誉 ─────────────
SCRIPT = PROOT / "scripts" / "hash_lock.sh"


def test_audit_mode_force_cold_install() -> None:
    """D-1:--audit 必须强制 cold 真下载验 hash(fresh temp venv + --no-cache + --require-hashes)。

    防 D-1 回退:有人把 --audit 改回 dry-run / 去掉 --no-cache / 复用 dev venv,
    本测试会红。冷装验 hash 是 --audit 的核心保证(uv 只在下载时验 hash)。
    """
    assert SCRIPT.is_file()
    text = SCRIPT.read_text()
    assert "--audit)" in text, "必须有 --audit 真审计模式(D-1 修复)"
    # 提取 --audit case 分支体(到下一分支 lock|"") 之前)
    start = text.index("--audit)")
    end = text.index('lock|"")')
    audit_body = text[start:end]
    assert "--no-cache" in audit_body, "--audit 必须用 --no-cache 强制冷下载(否则用缓存不验 hash)"
    assert "--require-hashes" in audit_body, "--audit 必须带 --require-hashes"
    assert "uv venv" in audit_body, "--audit 必须用 fresh temp venv(隔离 dev venv,不污染)"


def test_messages_disclose_no_hash_audit() -> None:
    """D-1:--verify/--apply 消息必须如实标注'不验 hash',不得过誉。"""
    text = SCRIPT.read_text()
    assert "未做 hash 审计" in text or "不下载" in text, "--verify 须披露 dry-run 不验 hash"
    assert "未验 hash" in text or "不验 hash" in text, "--apply 须披露 no-op 不验 hash"

